# Generated by Django 4.2.7 on 2026-01-14 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('WEEKLY_REPORT', 'Weekly Attendance Report'), ('LOW_ATTENDANCE_ALERT', 'Low Attendance Alert'), ('SYSTEM_NOTIFICATION', 'System Notification')], help_text='Type of notification email', max_length=50)),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Name of the recipient for personalization', max_length=255)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', help_text='Current delivery status', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of delivery attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('scheduled_at', models.DateTimeField(help_text='When the email was scheduled for delivery')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the final delivery failure occurred', null=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data for the email template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='email_notif_recipie_f9cd08_idx'), models.Index(fields=['notification_type', '-created_at'], name='email_notif_notific_cde178_idx'), models.Index(fields=['status', '-created_at'], name='email_notif_status_fac01b_idx')],
            },
        ),
    ]
