# Generated by Django 4.2.7 on 2026-01-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Enable uuid-ossp extension and set default for id column
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'ALTER TABLE users_user ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
            ],
            reverse_sql=[
                'ALTER TABLE users_user ALTER COLUMN id DROP DEFAULT;',
            ],
        ),
    ]
